version: '3'
services:
  bot:
    container_name: 'BullRunMinerBot'
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "node main.js"
    volumes:
      - .:/app